// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	hpaaggregatorv1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/hpaaggregator/v1alpha1"
	versioned "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubewharf/kubeadmiral/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/client/listers/hpaaggregator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ExternalMetricAdaptorInformer provides access to a shared informer and lister for
// ExternalMetricAdaptors.
type ExternalMetricAdaptorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ExternalMetricAdaptorLister
}

type externalMetricAdaptorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewExternalMetricAdaptorInformer constructs a new informer for ExternalMetricAdaptor type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewExternalMetricAdaptorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredExternalMetricAdaptorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredExternalMetricAdaptorInformer constructs a new informer for ExternalMetricAdaptor type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredExternalMetricAdaptorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HpaaggregatorV1alpha1().ExternalMetricAdaptors(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HpaaggregatorV1alpha1().ExternalMetricAdaptors(namespace).Watch(context.TODO(), options)
			},
		},
		&hpaaggregatorv1alpha1.ExternalMetricAdaptor{},
		resyncPeriod,
		indexers,
	)
}

func (f *externalMetricAdaptorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredExternalMetricAdaptorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *externalMetricAdaptorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hpaaggregatorv1alpha1.ExternalMetricAdaptor{}, f.defaultInformer)
}

func (f *externalMetricAdaptorInformer) Lister() v1alpha1.ExternalMetricAdaptorLister {
	return v1alpha1.NewExternalMetricAdaptorLister(f.Informer().GetIndexer())
}
