// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/hpaaggregator/v1alpha1"
	scheme "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ExternalMetricAdaptorsGetter has a method to return a ExternalMetricAdaptorInterface.
// A group's client should implement this interface.
type ExternalMetricAdaptorsGetter interface {
	ExternalMetricAdaptors(namespace string) ExternalMetricAdaptorInterface
}

// ExternalMetricAdaptorInterface has methods to work with ExternalMetricAdaptor resources.
type ExternalMetricAdaptorInterface interface {
	Create(ctx context.Context, externalMetricAdaptor *v1alpha1.ExternalMetricAdaptor, opts v1.CreateOptions) (*v1alpha1.ExternalMetricAdaptor, error)
	Update(ctx context.Context, externalMetricAdaptor *v1alpha1.ExternalMetricAdaptor, opts v1.UpdateOptions) (*v1alpha1.ExternalMetricAdaptor, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ExternalMetricAdaptor, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ExternalMetricAdaptorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ExternalMetricAdaptor, err error)
	ExternalMetricAdaptorExpansion
}

// externalMetricAdaptors implements ExternalMetricAdaptorInterface
type externalMetricAdaptors struct {
	client rest.Interface
	ns     string
}

// newExternalMetricAdaptors returns a ExternalMetricAdaptors
func newExternalMetricAdaptors(c *HpaaggregatorV1alpha1Client, namespace string) *externalMetricAdaptors {
	return &externalMetricAdaptors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the externalMetricAdaptor, and returns the corresponding externalMetricAdaptor object, and an error if there is any.
func (c *externalMetricAdaptors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ExternalMetricAdaptor, err error) {
	result = &v1alpha1.ExternalMetricAdaptor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("externalmetricadaptors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ExternalMetricAdaptors that match those selectors.
func (c *externalMetricAdaptors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ExternalMetricAdaptorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ExternalMetricAdaptorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("externalmetricadaptors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested externalMetricAdaptors.
func (c *externalMetricAdaptors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("externalmetricadaptors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a externalMetricAdaptor and creates it.  Returns the server's representation of the externalMetricAdaptor, and an error, if there is any.
func (c *externalMetricAdaptors) Create(ctx context.Context, externalMetricAdaptor *v1alpha1.ExternalMetricAdaptor, opts v1.CreateOptions) (result *v1alpha1.ExternalMetricAdaptor, err error) {
	result = &v1alpha1.ExternalMetricAdaptor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("externalmetricadaptors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(externalMetricAdaptor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a externalMetricAdaptor and updates it. Returns the server's representation of the externalMetricAdaptor, and an error, if there is any.
func (c *externalMetricAdaptors) Update(ctx context.Context, externalMetricAdaptor *v1alpha1.ExternalMetricAdaptor, opts v1.UpdateOptions) (result *v1alpha1.ExternalMetricAdaptor, err error) {
	result = &v1alpha1.ExternalMetricAdaptor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("externalmetricadaptors").
		Name(externalMetricAdaptor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(externalMetricAdaptor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the externalMetricAdaptor and deletes it. Returns an error if one occurs.
func (c *externalMetricAdaptors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("externalmetricadaptors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *externalMetricAdaptors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("externalmetricadaptors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched externalMetricAdaptor.
func (c *externalMetricAdaptors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ExternalMetricAdaptor, err error) {
	result = &v1alpha1.ExternalMetricAdaptor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("externalmetricadaptors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
