// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFederatedClusters implements FederatedClusterInterface
type FakeFederatedClusters struct {
	Fake *FakeCoreV1alpha1
}

var federatedclustersResource = schema.GroupVersionResource{Group: "core.kubeadmiral.io", Version: "v1alpha1", Resource: "federatedclusters"}

var federatedclustersKind = schema.GroupVersionKind{Group: "core.kubeadmiral.io", Version: "v1alpha1", Kind: "FederatedCluster"}

// Get takes name of the federatedCluster, and returns the corresponding federatedCluster object, and an error if there is any.
func (c *FakeFederatedClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FederatedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(federatedclustersResource, name), &v1alpha1.FederatedCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedCluster), err
}

// List takes label and field selectors, and returns the list of FederatedClusters that match those selectors.
func (c *FakeFederatedClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FederatedClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(federatedclustersResource, federatedclustersKind, opts), &v1alpha1.FederatedClusterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FederatedClusterList{ListMeta: obj.(*v1alpha1.FederatedClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.FederatedClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested federatedClusters.
func (c *FakeFederatedClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(federatedclustersResource, opts))
}

// Create takes the representation of a federatedCluster and creates it.  Returns the server's representation of the federatedCluster, and an error, if there is any.
func (c *FakeFederatedClusters) Create(ctx context.Context, federatedCluster *v1alpha1.FederatedCluster, opts v1.CreateOptions) (result *v1alpha1.FederatedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(federatedclustersResource, federatedCluster), &v1alpha1.FederatedCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedCluster), err
}

// Update takes the representation of a federatedCluster and updates it. Returns the server's representation of the federatedCluster, and an error, if there is any.
func (c *FakeFederatedClusters) Update(ctx context.Context, federatedCluster *v1alpha1.FederatedCluster, opts v1.UpdateOptions) (result *v1alpha1.FederatedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(federatedclustersResource, federatedCluster), &v1alpha1.FederatedCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFederatedClusters) UpdateStatus(ctx context.Context, federatedCluster *v1alpha1.FederatedCluster, opts v1.UpdateOptions) (*v1alpha1.FederatedCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(federatedclustersResource, "status", federatedCluster), &v1alpha1.FederatedCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedCluster), err
}

// Delete takes name of the federatedCluster and deletes it. Returns an error if one occurs.
func (c *FakeFederatedClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(federatedclustersResource, name, opts), &v1alpha1.FederatedCluster{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFederatedClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(federatedclustersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FederatedClusterList{})
	return err
}

// Patch applies the patch and returns the patched federatedCluster.
func (c *FakeFederatedClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FederatedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(federatedclustersResource, name, pt, data, subresources...), &v1alpha1.FederatedCluster{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedCluster), err
}
