// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCollectedStatuses implements CollectedStatusInterface
type FakeCollectedStatuses struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var collectedstatusesResource = schema.GroupVersionResource{Group: "core.kubeadmiral.io", Version: "v1alpha1", Resource: "collectedstatuses"}

var collectedstatusesKind = schema.GroupVersionKind{Group: "core.kubeadmiral.io", Version: "v1alpha1", Kind: "CollectedStatus"}

// Get takes name of the collectedStatus, and returns the corresponding collectedStatus object, and an error if there is any.
func (c *FakeCollectedStatuses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CollectedStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(collectedstatusesResource, c.ns, name), &v1alpha1.CollectedStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CollectedStatus), err
}

// List takes label and field selectors, and returns the list of CollectedStatuses that match those selectors.
func (c *FakeCollectedStatuses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CollectedStatusList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(collectedstatusesResource, collectedstatusesKind, c.ns, opts), &v1alpha1.CollectedStatusList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CollectedStatusList{ListMeta: obj.(*v1alpha1.CollectedStatusList).ListMeta}
	for _, item := range obj.(*v1alpha1.CollectedStatusList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested collectedStatuses.
func (c *FakeCollectedStatuses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(collectedstatusesResource, c.ns, opts))

}

// Create takes the representation of a collectedStatus and creates it.  Returns the server's representation of the collectedStatus, and an error, if there is any.
func (c *FakeCollectedStatuses) Create(ctx context.Context, collectedStatus *v1alpha1.CollectedStatus, opts v1.CreateOptions) (result *v1alpha1.CollectedStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(collectedstatusesResource, c.ns, collectedStatus), &v1alpha1.CollectedStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CollectedStatus), err
}

// Update takes the representation of a collectedStatus and updates it. Returns the server's representation of the collectedStatus, and an error, if there is any.
func (c *FakeCollectedStatuses) Update(ctx context.Context, collectedStatus *v1alpha1.CollectedStatus, opts v1.UpdateOptions) (result *v1alpha1.CollectedStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(collectedstatusesResource, c.ns, collectedStatus), &v1alpha1.CollectedStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CollectedStatus), err
}

// Delete takes name of the collectedStatus and deletes it. Returns an error if one occurs.
func (c *FakeCollectedStatuses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(collectedstatusesResource, c.ns, name, opts), &v1alpha1.CollectedStatus{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCollectedStatuses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(collectedstatusesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CollectedStatusList{})
	return err
}

// Patch applies the patch and returns the patched collectedStatus.
func (c *FakeCollectedStatuses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CollectedStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(collectedstatusesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CollectedStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CollectedStatus), err
}
