// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePropagatedVersions implements PropagatedVersionInterface
type FakePropagatedVersions struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var propagatedversionsResource = schema.GroupVersionResource{Group: "core.kubeadmiral.io", Version: "v1alpha1", Resource: "propagatedversions"}

var propagatedversionsKind = schema.GroupVersionKind{Group: "core.kubeadmiral.io", Version: "v1alpha1", Kind: "PropagatedVersion"}

// Get takes name of the propagatedVersion, and returns the corresponding propagatedVersion object, and an error if there is any.
func (c *FakePropagatedVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PropagatedVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(propagatedversionsResource, c.ns, name), &v1alpha1.PropagatedVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PropagatedVersion), err
}

// List takes label and field selectors, and returns the list of PropagatedVersions that match those selectors.
func (c *FakePropagatedVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PropagatedVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(propagatedversionsResource, propagatedversionsKind, c.ns, opts), &v1alpha1.PropagatedVersionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PropagatedVersionList{ListMeta: obj.(*v1alpha1.PropagatedVersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.PropagatedVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested propagatedVersions.
func (c *FakePropagatedVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(propagatedversionsResource, c.ns, opts))

}

// Create takes the representation of a propagatedVersion and creates it.  Returns the server's representation of the propagatedVersion, and an error, if there is any.
func (c *FakePropagatedVersions) Create(ctx context.Context, propagatedVersion *v1alpha1.PropagatedVersion, opts v1.CreateOptions) (result *v1alpha1.PropagatedVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(propagatedversionsResource, c.ns, propagatedVersion), &v1alpha1.PropagatedVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PropagatedVersion), err
}

// Update takes the representation of a propagatedVersion and updates it. Returns the server's representation of the propagatedVersion, and an error, if there is any.
func (c *FakePropagatedVersions) Update(ctx context.Context, propagatedVersion *v1alpha1.PropagatedVersion, opts v1.UpdateOptions) (result *v1alpha1.PropagatedVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(propagatedversionsResource, c.ns, propagatedVersion), &v1alpha1.PropagatedVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PropagatedVersion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePropagatedVersions) UpdateStatus(ctx context.Context, propagatedVersion *v1alpha1.PropagatedVersion, opts v1.UpdateOptions) (*v1alpha1.PropagatedVersion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(propagatedversionsResource, "status", c.ns, propagatedVersion), &v1alpha1.PropagatedVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PropagatedVersion), err
}

// Delete takes name of the propagatedVersion and deletes it. Returns an error if one occurs.
func (c *FakePropagatedVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(propagatedversionsResource, c.ns, name, opts), &v1alpha1.PropagatedVersion{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePropagatedVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(propagatedversionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PropagatedVersionList{})
	return err
}

// Patch applies the patch and returns the patched propagatedVersion.
func (c *FakePropagatedVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PropagatedVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(propagatedversionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PropagatedVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PropagatedVersion), err
}
