// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFederatedObjects implements FederatedObjectInterface
type FakeFederatedObjects struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var federatedobjectsResource = schema.GroupVersionResource{Group: "core.kubeadmiral.io", Version: "v1alpha1", Resource: "federatedobjects"}

var federatedobjectsKind = schema.GroupVersionKind{Group: "core.kubeadmiral.io", Version: "v1alpha1", Kind: "FederatedObject"}

// Get takes name of the federatedObject, and returns the corresponding federatedObject object, and an error if there is any.
func (c *FakeFederatedObjects) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FederatedObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(federatedobjectsResource, c.ns, name), &v1alpha1.FederatedObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedObject), err
}

// List takes label and field selectors, and returns the list of FederatedObjects that match those selectors.
func (c *FakeFederatedObjects) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FederatedObjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(federatedobjectsResource, federatedobjectsKind, c.ns, opts), &v1alpha1.FederatedObjectList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FederatedObjectList{ListMeta: obj.(*v1alpha1.FederatedObjectList).ListMeta}
	for _, item := range obj.(*v1alpha1.FederatedObjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested federatedObjects.
func (c *FakeFederatedObjects) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(federatedobjectsResource, c.ns, opts))

}

// Create takes the representation of a federatedObject and creates it.  Returns the server's representation of the federatedObject, and an error, if there is any.
func (c *FakeFederatedObjects) Create(ctx context.Context, federatedObject *v1alpha1.FederatedObject, opts v1.CreateOptions) (result *v1alpha1.FederatedObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(federatedobjectsResource, c.ns, federatedObject), &v1alpha1.FederatedObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedObject), err
}

// Update takes the representation of a federatedObject and updates it. Returns the server's representation of the federatedObject, and an error, if there is any.
func (c *FakeFederatedObjects) Update(ctx context.Context, federatedObject *v1alpha1.FederatedObject, opts v1.UpdateOptions) (result *v1alpha1.FederatedObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(federatedobjectsResource, c.ns, federatedObject), &v1alpha1.FederatedObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedObject), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFederatedObjects) UpdateStatus(ctx context.Context, federatedObject *v1alpha1.FederatedObject, opts v1.UpdateOptions) (*v1alpha1.FederatedObject, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(federatedobjectsResource, "status", c.ns, federatedObject), &v1alpha1.FederatedObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedObject), err
}

// Delete takes name of the federatedObject and deletes it. Returns an error if one occurs.
func (c *FakeFederatedObjects) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(federatedobjectsResource, c.ns, name, opts), &v1alpha1.FederatedObject{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFederatedObjects) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(federatedobjectsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FederatedObjectList{})
	return err
}

// Patch applies the patch and returns the patched federatedObject.
func (c *FakeFederatedObjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FederatedObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(federatedobjectsResource, c.ns, name, pt, data, subresources...), &v1alpha1.FederatedObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedObject), err
}
