// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterPropagatedVersions implements ClusterPropagatedVersionInterface
type FakeClusterPropagatedVersions struct {
	Fake *FakeCoreV1alpha1
}

var clusterpropagatedversionsResource = schema.GroupVersionResource{Group: "core.kubeadmiral.io", Version: "v1alpha1", Resource: "clusterpropagatedversions"}

var clusterpropagatedversionsKind = schema.GroupVersionKind{Group: "core.kubeadmiral.io", Version: "v1alpha1", Kind: "ClusterPropagatedVersion"}

// Get takes name of the clusterPropagatedVersion, and returns the corresponding clusterPropagatedVersion object, and an error if there is any.
func (c *FakeClusterPropagatedVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterPropagatedVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterpropagatedversionsResource, name), &v1alpha1.ClusterPropagatedVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterPropagatedVersion), err
}

// List takes label and field selectors, and returns the list of ClusterPropagatedVersions that match those selectors.
func (c *FakeClusterPropagatedVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterPropagatedVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterpropagatedversionsResource, clusterpropagatedversionsKind, opts), &v1alpha1.ClusterPropagatedVersionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterPropagatedVersionList{ListMeta: obj.(*v1alpha1.ClusterPropagatedVersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterPropagatedVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterPropagatedVersions.
func (c *FakeClusterPropagatedVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterpropagatedversionsResource, opts))
}

// Create takes the representation of a clusterPropagatedVersion and creates it.  Returns the server's representation of the clusterPropagatedVersion, and an error, if there is any.
func (c *FakeClusterPropagatedVersions) Create(ctx context.Context, clusterPropagatedVersion *v1alpha1.ClusterPropagatedVersion, opts v1.CreateOptions) (result *v1alpha1.ClusterPropagatedVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterpropagatedversionsResource, clusterPropagatedVersion), &v1alpha1.ClusterPropagatedVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterPropagatedVersion), err
}

// Update takes the representation of a clusterPropagatedVersion and updates it. Returns the server's representation of the clusterPropagatedVersion, and an error, if there is any.
func (c *FakeClusterPropagatedVersions) Update(ctx context.Context, clusterPropagatedVersion *v1alpha1.ClusterPropagatedVersion, opts v1.UpdateOptions) (result *v1alpha1.ClusterPropagatedVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterpropagatedversionsResource, clusterPropagatedVersion), &v1alpha1.ClusterPropagatedVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterPropagatedVersion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterPropagatedVersions) UpdateStatus(ctx context.Context, clusterPropagatedVersion *v1alpha1.ClusterPropagatedVersion, opts v1.UpdateOptions) (*v1alpha1.ClusterPropagatedVersion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterpropagatedversionsResource, "status", clusterPropagatedVersion), &v1alpha1.ClusterPropagatedVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterPropagatedVersion), err
}

// Delete takes name of the clusterPropagatedVersion and deletes it. Returns an error if one occurs.
func (c *FakeClusterPropagatedVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterpropagatedversionsResource, name, opts), &v1alpha1.ClusterPropagatedVersion{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterPropagatedVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterpropagatedversionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterPropagatedVersionList{})
	return err
}

// Patch applies the patch and returns the patched clusterPropagatedVersion.
func (c *FakeClusterPropagatedVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterPropagatedVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterpropagatedversionsResource, name, pt, data, subresources...), &v1alpha1.ClusterPropagatedVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterPropagatedVersion), err
}
