// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFederatedTypeConfigs implements FederatedTypeConfigInterface
type FakeFederatedTypeConfigs struct {
	Fake *FakeCoreV1alpha1
}

var federatedtypeconfigsResource = schema.GroupVersionResource{Group: "core.kubeadmiral.io", Version: "v1alpha1", Resource: "federatedtypeconfigs"}

var federatedtypeconfigsKind = schema.GroupVersionKind{Group: "core.kubeadmiral.io", Version: "v1alpha1", Kind: "FederatedTypeConfig"}

// Get takes name of the federatedTypeConfig, and returns the corresponding federatedTypeConfig object, and an error if there is any.
func (c *FakeFederatedTypeConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FederatedTypeConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(federatedtypeconfigsResource, name), &v1alpha1.FederatedTypeConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedTypeConfig), err
}

// List takes label and field selectors, and returns the list of FederatedTypeConfigs that match those selectors.
func (c *FakeFederatedTypeConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FederatedTypeConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(federatedtypeconfigsResource, federatedtypeconfigsKind, opts), &v1alpha1.FederatedTypeConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FederatedTypeConfigList{ListMeta: obj.(*v1alpha1.FederatedTypeConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.FederatedTypeConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested federatedTypeConfigs.
func (c *FakeFederatedTypeConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(federatedtypeconfigsResource, opts))
}

// Create takes the representation of a federatedTypeConfig and creates it.  Returns the server's representation of the federatedTypeConfig, and an error, if there is any.
func (c *FakeFederatedTypeConfigs) Create(ctx context.Context, federatedTypeConfig *v1alpha1.FederatedTypeConfig, opts v1.CreateOptions) (result *v1alpha1.FederatedTypeConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(federatedtypeconfigsResource, federatedTypeConfig), &v1alpha1.FederatedTypeConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedTypeConfig), err
}

// Update takes the representation of a federatedTypeConfig and updates it. Returns the server's representation of the federatedTypeConfig, and an error, if there is any.
func (c *FakeFederatedTypeConfigs) Update(ctx context.Context, federatedTypeConfig *v1alpha1.FederatedTypeConfig, opts v1.UpdateOptions) (result *v1alpha1.FederatedTypeConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(federatedtypeconfigsResource, federatedTypeConfig), &v1alpha1.FederatedTypeConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedTypeConfig), err
}

// Delete takes name of the federatedTypeConfig and deletes it. Returns an error if one occurs.
func (c *FakeFederatedTypeConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(federatedtypeconfigsResource, name, opts), &v1alpha1.FederatedTypeConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFederatedTypeConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(federatedtypeconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FederatedTypeConfigList{})
	return err
}

// Patch applies the patch and returns the patched federatedTypeConfig.
func (c *FakeFederatedTypeConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FederatedTypeConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(federatedtypeconfigsResource, name, pt, data, subresources...), &v1alpha1.FederatedTypeConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FederatedTypeConfig), err
}
