// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterFederatedObjects implements ClusterFederatedObjectInterface
type FakeClusterFederatedObjects struct {
	Fake *FakeCoreV1alpha1
}

var clusterfederatedobjectsResource = schema.GroupVersionResource{Group: "core.kubeadmiral.io", Version: "v1alpha1", Resource: "clusterfederatedobjects"}

var clusterfederatedobjectsKind = schema.GroupVersionKind{Group: "core.kubeadmiral.io", Version: "v1alpha1", Kind: "ClusterFederatedObject"}

// Get takes name of the clusterFederatedObject, and returns the corresponding clusterFederatedObject object, and an error if there is any.
func (c *FakeClusterFederatedObjects) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterFederatedObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterfederatedobjectsResource, name), &v1alpha1.ClusterFederatedObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterFederatedObject), err
}

// List takes label and field selectors, and returns the list of ClusterFederatedObjects that match those selectors.
func (c *FakeClusterFederatedObjects) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterFederatedObjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterfederatedobjectsResource, clusterfederatedobjectsKind, opts), &v1alpha1.ClusterFederatedObjectList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterFederatedObjectList{ListMeta: obj.(*v1alpha1.ClusterFederatedObjectList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterFederatedObjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterFederatedObjects.
func (c *FakeClusterFederatedObjects) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterfederatedobjectsResource, opts))
}

// Create takes the representation of a clusterFederatedObject and creates it.  Returns the server's representation of the clusterFederatedObject, and an error, if there is any.
func (c *FakeClusterFederatedObjects) Create(ctx context.Context, clusterFederatedObject *v1alpha1.ClusterFederatedObject, opts v1.CreateOptions) (result *v1alpha1.ClusterFederatedObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterfederatedobjectsResource, clusterFederatedObject), &v1alpha1.ClusterFederatedObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterFederatedObject), err
}

// Update takes the representation of a clusterFederatedObject and updates it. Returns the server's representation of the clusterFederatedObject, and an error, if there is any.
func (c *FakeClusterFederatedObjects) Update(ctx context.Context, clusterFederatedObject *v1alpha1.ClusterFederatedObject, opts v1.UpdateOptions) (result *v1alpha1.ClusterFederatedObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterfederatedobjectsResource, clusterFederatedObject), &v1alpha1.ClusterFederatedObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterFederatedObject), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterFederatedObjects) UpdateStatus(ctx context.Context, clusterFederatedObject *v1alpha1.ClusterFederatedObject, opts v1.UpdateOptions) (*v1alpha1.ClusterFederatedObject, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterfederatedobjectsResource, "status", clusterFederatedObject), &v1alpha1.ClusterFederatedObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterFederatedObject), err
}

// Delete takes name of the clusterFederatedObject and deletes it. Returns an error if one occurs.
func (c *FakeClusterFederatedObjects) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterfederatedobjectsResource, name, opts), &v1alpha1.ClusterFederatedObject{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterFederatedObjects) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterfederatedobjectsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterFederatedObjectList{})
	return err
}

// Patch applies the patch and returns the patched clusterFederatedObject.
func (c *FakeClusterFederatedObjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterFederatedObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterfederatedobjectsResource, name, pt, data, subresources...), &v1alpha1.ClusterFederatedObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterFederatedObject), err
}
