// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	scheme "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterCollectedStatusesGetter has a method to return a ClusterCollectedStatusInterface.
// A group's client should implement this interface.
type ClusterCollectedStatusesGetter interface {
	ClusterCollectedStatuses() ClusterCollectedStatusInterface
}

// ClusterCollectedStatusInterface has methods to work with ClusterCollectedStatus resources.
type ClusterCollectedStatusInterface interface {
	Create(ctx context.Context, clusterCollectedStatus *v1alpha1.ClusterCollectedStatus, opts v1.CreateOptions) (*v1alpha1.ClusterCollectedStatus, error)
	Update(ctx context.Context, clusterCollectedStatus *v1alpha1.ClusterCollectedStatus, opts v1.UpdateOptions) (*v1alpha1.ClusterCollectedStatus, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterCollectedStatus, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterCollectedStatusList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterCollectedStatus, err error)
	ClusterCollectedStatusExpansion
}

// clusterCollectedStatuses implements ClusterCollectedStatusInterface
type clusterCollectedStatuses struct {
	client rest.Interface
}

// newClusterCollectedStatuses returns a ClusterCollectedStatuses
func newClusterCollectedStatuses(c *CoreV1alpha1Client) *clusterCollectedStatuses {
	return &clusterCollectedStatuses{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterCollectedStatus, and returns the corresponding clusterCollectedStatus object, and an error if there is any.
func (c *clusterCollectedStatuses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterCollectedStatus, err error) {
	result = &v1alpha1.ClusterCollectedStatus{}
	err = c.client.Get().
		Resource("clustercollectedstatuses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterCollectedStatuses that match those selectors.
func (c *clusterCollectedStatuses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterCollectedStatusList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterCollectedStatusList{}
	err = c.client.Get().
		Resource("clustercollectedstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterCollectedStatuses.
func (c *clusterCollectedStatuses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clustercollectedstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterCollectedStatus and creates it.  Returns the server's representation of the clusterCollectedStatus, and an error, if there is any.
func (c *clusterCollectedStatuses) Create(ctx context.Context, clusterCollectedStatus *v1alpha1.ClusterCollectedStatus, opts v1.CreateOptions) (result *v1alpha1.ClusterCollectedStatus, err error) {
	result = &v1alpha1.ClusterCollectedStatus{}
	err = c.client.Post().
		Resource("clustercollectedstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterCollectedStatus).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterCollectedStatus and updates it. Returns the server's representation of the clusterCollectedStatus, and an error, if there is any.
func (c *clusterCollectedStatuses) Update(ctx context.Context, clusterCollectedStatus *v1alpha1.ClusterCollectedStatus, opts v1.UpdateOptions) (result *v1alpha1.ClusterCollectedStatus, err error) {
	result = &v1alpha1.ClusterCollectedStatus{}
	err = c.client.Put().
		Resource("clustercollectedstatuses").
		Name(clusterCollectedStatus.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterCollectedStatus).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterCollectedStatus and deletes it. Returns an error if one occurs.
func (c *clusterCollectedStatuses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clustercollectedstatuses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterCollectedStatuses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clustercollectedstatuses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterCollectedStatus.
func (c *clusterCollectedStatuses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterCollectedStatus, err error) {
	result = &v1alpha1.ClusterCollectedStatus{}
	err = c.client.Patch(pt).
		Resource("clustercollectedstatuses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
