// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	scheme "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterFederatedObjectsGetter has a method to return a ClusterFederatedObjectInterface.
// A group's client should implement this interface.
type ClusterFederatedObjectsGetter interface {
	ClusterFederatedObjects() ClusterFederatedObjectInterface
}

// ClusterFederatedObjectInterface has methods to work with ClusterFederatedObject resources.
type ClusterFederatedObjectInterface interface {
	Create(ctx context.Context, clusterFederatedObject *v1alpha1.ClusterFederatedObject, opts v1.CreateOptions) (*v1alpha1.ClusterFederatedObject, error)
	Update(ctx context.Context, clusterFederatedObject *v1alpha1.ClusterFederatedObject, opts v1.UpdateOptions) (*v1alpha1.ClusterFederatedObject, error)
	UpdateStatus(ctx context.Context, clusterFederatedObject *v1alpha1.ClusterFederatedObject, opts v1.UpdateOptions) (*v1alpha1.ClusterFederatedObject, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterFederatedObject, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterFederatedObjectList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterFederatedObject, err error)
	ClusterFederatedObjectExpansion
}

// clusterFederatedObjects implements ClusterFederatedObjectInterface
type clusterFederatedObjects struct {
	client rest.Interface
}

// newClusterFederatedObjects returns a ClusterFederatedObjects
func newClusterFederatedObjects(c *CoreV1alpha1Client) *clusterFederatedObjects {
	return &clusterFederatedObjects{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterFederatedObject, and returns the corresponding clusterFederatedObject object, and an error if there is any.
func (c *clusterFederatedObjects) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterFederatedObject, err error) {
	result = &v1alpha1.ClusterFederatedObject{}
	err = c.client.Get().
		Resource("clusterfederatedobjects").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterFederatedObjects that match those selectors.
func (c *clusterFederatedObjects) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterFederatedObjectList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterFederatedObjectList{}
	err = c.client.Get().
		Resource("clusterfederatedobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterFederatedObjects.
func (c *clusterFederatedObjects) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterfederatedobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterFederatedObject and creates it.  Returns the server's representation of the clusterFederatedObject, and an error, if there is any.
func (c *clusterFederatedObjects) Create(ctx context.Context, clusterFederatedObject *v1alpha1.ClusterFederatedObject, opts v1.CreateOptions) (result *v1alpha1.ClusterFederatedObject, err error) {
	result = &v1alpha1.ClusterFederatedObject{}
	err = c.client.Post().
		Resource("clusterfederatedobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterFederatedObject).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterFederatedObject and updates it. Returns the server's representation of the clusterFederatedObject, and an error, if there is any.
func (c *clusterFederatedObjects) Update(ctx context.Context, clusterFederatedObject *v1alpha1.ClusterFederatedObject, opts v1.UpdateOptions) (result *v1alpha1.ClusterFederatedObject, err error) {
	result = &v1alpha1.ClusterFederatedObject{}
	err = c.client.Put().
		Resource("clusterfederatedobjects").
		Name(clusterFederatedObject.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterFederatedObject).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterFederatedObjects) UpdateStatus(ctx context.Context, clusterFederatedObject *v1alpha1.ClusterFederatedObject, opts v1.UpdateOptions) (result *v1alpha1.ClusterFederatedObject, err error) {
	result = &v1alpha1.ClusterFederatedObject{}
	err = c.client.Put().
		Resource("clusterfederatedobjects").
		Name(clusterFederatedObject.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterFederatedObject).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterFederatedObject and deletes it. Returns an error if one occurs.
func (c *clusterFederatedObjects) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterfederatedobjects").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterFederatedObjects) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterfederatedobjects").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterFederatedObject.
func (c *clusterFederatedObjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterFederatedObject, err error) {
	result = &v1alpha1.ClusterFederatedObject{}
	err = c.client.Patch(pt).
		Resource("clusterfederatedobjects").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
