// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	scheme "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FederatedObjectsGetter has a method to return a FederatedObjectInterface.
// A group's client should implement this interface.
type FederatedObjectsGetter interface {
	FederatedObjects(namespace string) FederatedObjectInterface
}

// FederatedObjectInterface has methods to work with FederatedObject resources.
type FederatedObjectInterface interface {
	Create(ctx context.Context, federatedObject *v1alpha1.FederatedObject, opts v1.CreateOptions) (*v1alpha1.FederatedObject, error)
	Update(ctx context.Context, federatedObject *v1alpha1.FederatedObject, opts v1.UpdateOptions) (*v1alpha1.FederatedObject, error)
	UpdateStatus(ctx context.Context, federatedObject *v1alpha1.FederatedObject, opts v1.UpdateOptions) (*v1alpha1.FederatedObject, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FederatedObject, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FederatedObjectList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FederatedObject, err error)
	FederatedObjectExpansion
}

// federatedObjects implements FederatedObjectInterface
type federatedObjects struct {
	client rest.Interface
	ns     string
}

// newFederatedObjects returns a FederatedObjects
func newFederatedObjects(c *CoreV1alpha1Client, namespace string) *federatedObjects {
	return &federatedObjects{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the federatedObject, and returns the corresponding federatedObject object, and an error if there is any.
func (c *federatedObjects) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FederatedObject, err error) {
	result = &v1alpha1.FederatedObject{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("federatedobjects").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FederatedObjects that match those selectors.
func (c *federatedObjects) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FederatedObjectList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FederatedObjectList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("federatedobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested federatedObjects.
func (c *federatedObjects) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("federatedobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a federatedObject and creates it.  Returns the server's representation of the federatedObject, and an error, if there is any.
func (c *federatedObjects) Create(ctx context.Context, federatedObject *v1alpha1.FederatedObject, opts v1.CreateOptions) (result *v1alpha1.FederatedObject, err error) {
	result = &v1alpha1.FederatedObject{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("federatedobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedObject).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a federatedObject and updates it. Returns the server's representation of the federatedObject, and an error, if there is any.
func (c *federatedObjects) Update(ctx context.Context, federatedObject *v1alpha1.FederatedObject, opts v1.UpdateOptions) (result *v1alpha1.FederatedObject, err error) {
	result = &v1alpha1.FederatedObject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("federatedobjects").
		Name(federatedObject.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedObject).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *federatedObjects) UpdateStatus(ctx context.Context, federatedObject *v1alpha1.FederatedObject, opts v1.UpdateOptions) (result *v1alpha1.FederatedObject, err error) {
	result = &v1alpha1.FederatedObject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("federatedobjects").
		Name(federatedObject.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedObject).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the federatedObject and deletes it. Returns an error if one occurs.
func (c *federatedObjects) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("federatedobjects").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *federatedObjects) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("federatedobjects").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched federatedObject.
func (c *federatedObjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FederatedObject, err error) {
	result = &v1alpha1.FederatedObject{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("federatedobjects").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
