// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	scheme "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FederatedTypeConfigsGetter has a method to return a FederatedTypeConfigInterface.
// A group's client should implement this interface.
type FederatedTypeConfigsGetter interface {
	FederatedTypeConfigs() FederatedTypeConfigInterface
}

// FederatedTypeConfigInterface has methods to work with FederatedTypeConfig resources.
type FederatedTypeConfigInterface interface {
	Create(ctx context.Context, federatedTypeConfig *v1alpha1.FederatedTypeConfig, opts v1.CreateOptions) (*v1alpha1.FederatedTypeConfig, error)
	Update(ctx context.Context, federatedTypeConfig *v1alpha1.FederatedTypeConfig, opts v1.UpdateOptions) (*v1alpha1.FederatedTypeConfig, error)
	UpdateStatus(ctx context.Context, federatedTypeConfig *v1alpha1.FederatedTypeConfig, opts v1.UpdateOptions) (*v1alpha1.FederatedTypeConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FederatedTypeConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FederatedTypeConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FederatedTypeConfig, err error)
	FederatedTypeConfigExpansion
}

// federatedTypeConfigs implements FederatedTypeConfigInterface
type federatedTypeConfigs struct {
	client rest.Interface
}

// newFederatedTypeConfigs returns a FederatedTypeConfigs
func newFederatedTypeConfigs(c *CoreV1alpha1Client) *federatedTypeConfigs {
	return &federatedTypeConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the federatedTypeConfig, and returns the corresponding federatedTypeConfig object, and an error if there is any.
func (c *federatedTypeConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FederatedTypeConfig, err error) {
	result = &v1alpha1.FederatedTypeConfig{}
	err = c.client.Get().
		Resource("federatedtypeconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FederatedTypeConfigs that match those selectors.
func (c *federatedTypeConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FederatedTypeConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FederatedTypeConfigList{}
	err = c.client.Get().
		Resource("federatedtypeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested federatedTypeConfigs.
func (c *federatedTypeConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("federatedtypeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a federatedTypeConfig and creates it.  Returns the server's representation of the federatedTypeConfig, and an error, if there is any.
func (c *federatedTypeConfigs) Create(ctx context.Context, federatedTypeConfig *v1alpha1.FederatedTypeConfig, opts v1.CreateOptions) (result *v1alpha1.FederatedTypeConfig, err error) {
	result = &v1alpha1.FederatedTypeConfig{}
	err = c.client.Post().
		Resource("federatedtypeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedTypeConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a federatedTypeConfig and updates it. Returns the server's representation of the federatedTypeConfig, and an error, if there is any.
func (c *federatedTypeConfigs) Update(ctx context.Context, federatedTypeConfig *v1alpha1.FederatedTypeConfig, opts v1.UpdateOptions) (result *v1alpha1.FederatedTypeConfig, err error) {
	result = &v1alpha1.FederatedTypeConfig{}
	err = c.client.Put().
		Resource("federatedtypeconfigs").
		Name(federatedTypeConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedTypeConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *federatedTypeConfigs) UpdateStatus(ctx context.Context, federatedTypeConfig *v1alpha1.FederatedTypeConfig, opts v1.UpdateOptions) (result *v1alpha1.FederatedTypeConfig, err error) {
	result = &v1alpha1.FederatedTypeConfig{}
	err = c.client.Put().
		Resource("federatedtypeconfigs").
		Name(federatedTypeConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedTypeConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the federatedTypeConfig and deletes it. Returns an error if one occurs.
func (c *federatedTypeConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("federatedtypeconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *federatedTypeConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("federatedtypeconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched federatedTypeConfig.
func (c *federatedTypeConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FederatedTypeConfig, err error) {
	result = &v1alpha1.FederatedTypeConfig{}
	err = c.client.Patch(pt).
		Resource("federatedtypeconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
