// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	scheme "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FederatedClustersGetter has a method to return a FederatedClusterInterface.
// A group's client should implement this interface.
type FederatedClustersGetter interface {
	FederatedClusters() FederatedClusterInterface
}

// FederatedClusterInterface has methods to work with FederatedCluster resources.
type FederatedClusterInterface interface {
	Create(ctx context.Context, federatedCluster *v1alpha1.FederatedCluster, opts v1.CreateOptions) (*v1alpha1.FederatedCluster, error)
	Update(ctx context.Context, federatedCluster *v1alpha1.FederatedCluster, opts v1.UpdateOptions) (*v1alpha1.FederatedCluster, error)
	UpdateStatus(ctx context.Context, federatedCluster *v1alpha1.FederatedCluster, opts v1.UpdateOptions) (*v1alpha1.FederatedCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FederatedCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FederatedClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FederatedCluster, err error)
	FederatedClusterExpansion
}

// federatedClusters implements FederatedClusterInterface
type federatedClusters struct {
	client rest.Interface
}

// newFederatedClusters returns a FederatedClusters
func newFederatedClusters(c *CoreV1alpha1Client) *federatedClusters {
	return &federatedClusters{
		client: c.RESTClient(),
	}
}

// Get takes name of the federatedCluster, and returns the corresponding federatedCluster object, and an error if there is any.
func (c *federatedClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FederatedCluster, err error) {
	result = &v1alpha1.FederatedCluster{}
	err = c.client.Get().
		Resource("federatedclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FederatedClusters that match those selectors.
func (c *federatedClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FederatedClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FederatedClusterList{}
	err = c.client.Get().
		Resource("federatedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested federatedClusters.
func (c *federatedClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("federatedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a federatedCluster and creates it.  Returns the server's representation of the federatedCluster, and an error, if there is any.
func (c *federatedClusters) Create(ctx context.Context, federatedCluster *v1alpha1.FederatedCluster, opts v1.CreateOptions) (result *v1alpha1.FederatedCluster, err error) {
	result = &v1alpha1.FederatedCluster{}
	err = c.client.Post().
		Resource("federatedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a federatedCluster and updates it. Returns the server's representation of the federatedCluster, and an error, if there is any.
func (c *federatedClusters) Update(ctx context.Context, federatedCluster *v1alpha1.FederatedCluster, opts v1.UpdateOptions) (result *v1alpha1.FederatedCluster, err error) {
	result = &v1alpha1.FederatedCluster{}
	err = c.client.Put().
		Resource("federatedclusters").
		Name(federatedCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *federatedClusters) UpdateStatus(ctx context.Context, federatedCluster *v1alpha1.FederatedCluster, opts v1.UpdateOptions) (result *v1alpha1.FederatedCluster, err error) {
	result = &v1alpha1.FederatedCluster{}
	err = c.client.Put().
		Resource("federatedclusters").
		Name(federatedCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the federatedCluster and deletes it. Returns an error if one occurs.
func (c *federatedClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("federatedclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *federatedClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("federatedclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched federatedCluster.
func (c *federatedClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FederatedCluster, err error) {
	result = &v1alpha1.FederatedCluster{}
	err = c.client.Patch(pt).
		Resource("federatedclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
