// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterCollectedStatusExpansion interface{}

type ClusterFederatedObjectExpansion interface{}

type ClusterOverridePolicyExpansion interface{}

type ClusterPropagatedVersionExpansion interface{}

type ClusterPropagationPolicyExpansion interface{}

type CollectedStatusExpansion interface{}

type FederatedClusterExpansion interface{}

type FederatedObjectExpansion interface{}

type FederatedTypeConfigExpansion interface{}

type OverridePolicyExpansion interface{}

type PropagatedVersionExpansion interface{}

type PropagationPolicyExpansion interface{}

type SchedulerPluginWebhookConfigurationExpansion interface{}

type SchedulingProfileExpansion interface{}
