// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	scheme "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PropagatedVersionsGetter has a method to return a PropagatedVersionInterface.
// A group's client should implement this interface.
type PropagatedVersionsGetter interface {
	PropagatedVersions(namespace string) PropagatedVersionInterface
}

// PropagatedVersionInterface has methods to work with PropagatedVersion resources.
type PropagatedVersionInterface interface {
	Create(ctx context.Context, propagatedVersion *v1alpha1.PropagatedVersion, opts v1.CreateOptions) (*v1alpha1.PropagatedVersion, error)
	Update(ctx context.Context, propagatedVersion *v1alpha1.PropagatedVersion, opts v1.UpdateOptions) (*v1alpha1.PropagatedVersion, error)
	UpdateStatus(ctx context.Context, propagatedVersion *v1alpha1.PropagatedVersion, opts v1.UpdateOptions) (*v1alpha1.PropagatedVersion, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PropagatedVersion, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PropagatedVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PropagatedVersion, err error)
	PropagatedVersionExpansion
}

// propagatedVersions implements PropagatedVersionInterface
type propagatedVersions struct {
	client rest.Interface
	ns     string
}

// newPropagatedVersions returns a PropagatedVersions
func newPropagatedVersions(c *CoreV1alpha1Client, namespace string) *propagatedVersions {
	return &propagatedVersions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the propagatedVersion, and returns the corresponding propagatedVersion object, and an error if there is any.
func (c *propagatedVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PropagatedVersion, err error) {
	result = &v1alpha1.PropagatedVersion{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("propagatedversions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PropagatedVersions that match those selectors.
func (c *propagatedVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PropagatedVersionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PropagatedVersionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("propagatedversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested propagatedVersions.
func (c *propagatedVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("propagatedversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a propagatedVersion and creates it.  Returns the server's representation of the propagatedVersion, and an error, if there is any.
func (c *propagatedVersions) Create(ctx context.Context, propagatedVersion *v1alpha1.PropagatedVersion, opts v1.CreateOptions) (result *v1alpha1.PropagatedVersion, err error) {
	result = &v1alpha1.PropagatedVersion{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("propagatedversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(propagatedVersion).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a propagatedVersion and updates it. Returns the server's representation of the propagatedVersion, and an error, if there is any.
func (c *propagatedVersions) Update(ctx context.Context, propagatedVersion *v1alpha1.PropagatedVersion, opts v1.UpdateOptions) (result *v1alpha1.PropagatedVersion, err error) {
	result = &v1alpha1.PropagatedVersion{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("propagatedversions").
		Name(propagatedVersion.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(propagatedVersion).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *propagatedVersions) UpdateStatus(ctx context.Context, propagatedVersion *v1alpha1.PropagatedVersion, opts v1.UpdateOptions) (result *v1alpha1.PropagatedVersion, err error) {
	result = &v1alpha1.PropagatedVersion{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("propagatedversions").
		Name(propagatedVersion.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(propagatedVersion).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the propagatedVersion and deletes it. Returns an error if one occurs.
func (c *propagatedVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("propagatedversions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *propagatedVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("propagatedversions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched propagatedVersion.
func (c *propagatedVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PropagatedVersion, err error) {
	result = &v1alpha1.PropagatedVersion{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("propagatedversions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
