// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	scheme "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SchedulingProfilesGetter has a method to return a SchedulingProfileInterface.
// A group's client should implement this interface.
type SchedulingProfilesGetter interface {
	SchedulingProfiles() SchedulingProfileInterface
}

// SchedulingProfileInterface has methods to work with SchedulingProfile resources.
type SchedulingProfileInterface interface {
	Create(ctx context.Context, schedulingProfile *v1alpha1.SchedulingProfile, opts v1.CreateOptions) (*v1alpha1.SchedulingProfile, error)
	Update(ctx context.Context, schedulingProfile *v1alpha1.SchedulingProfile, opts v1.UpdateOptions) (*v1alpha1.SchedulingProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SchedulingProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SchedulingProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SchedulingProfile, err error)
	SchedulingProfileExpansion
}

// schedulingProfiles implements SchedulingProfileInterface
type schedulingProfiles struct {
	client rest.Interface
}

// newSchedulingProfiles returns a SchedulingProfiles
func newSchedulingProfiles(c *CoreV1alpha1Client) *schedulingProfiles {
	return &schedulingProfiles{
		client: c.RESTClient(),
	}
}

// Get takes name of the schedulingProfile, and returns the corresponding schedulingProfile object, and an error if there is any.
func (c *schedulingProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SchedulingProfile, err error) {
	result = &v1alpha1.SchedulingProfile{}
	err = c.client.Get().
		Resource("schedulingprofiles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SchedulingProfiles that match those selectors.
func (c *schedulingProfiles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SchedulingProfileList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SchedulingProfileList{}
	err = c.client.Get().
		Resource("schedulingprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested schedulingProfiles.
func (c *schedulingProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("schedulingprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a schedulingProfile and creates it.  Returns the server's representation of the schedulingProfile, and an error, if there is any.
func (c *schedulingProfiles) Create(ctx context.Context, schedulingProfile *v1alpha1.SchedulingProfile, opts v1.CreateOptions) (result *v1alpha1.SchedulingProfile, err error) {
	result = &v1alpha1.SchedulingProfile{}
	err = c.client.Post().
		Resource("schedulingprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(schedulingProfile).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a schedulingProfile and updates it. Returns the server's representation of the schedulingProfile, and an error, if there is any.
func (c *schedulingProfiles) Update(ctx context.Context, schedulingProfile *v1alpha1.SchedulingProfile, opts v1.UpdateOptions) (result *v1alpha1.SchedulingProfile, err error) {
	result = &v1alpha1.SchedulingProfile{}
	err = c.client.Put().
		Resource("schedulingprofiles").
		Name(schedulingProfile.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(schedulingProfile).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the schedulingProfile and deletes it. Returns an error if one occurs.
func (c *schedulingProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("schedulingprofiles").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *schedulingProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("schedulingprofiles").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched schedulingProfile.
func (c *schedulingProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SchedulingProfile, err error) {
	result = &v1alpha1.SchedulingProfile{}
	err = c.client.Patch(pt).
		Resource("schedulingprofiles").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
