// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ExternalMetricAdaptorListerExpansion allows custom methods to be added to
// ExternalMetricAdaptorLister.
type ExternalMetricAdaptorListerExpansion interface{}

// ExternalMetricAdaptorNamespaceListerExpansion allows custom methods to be added to
// ExternalMetricAdaptorNamespaceLister.
type ExternalMetricAdaptorNamespaceListerExpansion interface{}
