// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	corev1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	versioned "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubewharf/kubeadmiral/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/client/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterPropagatedVersionInformer provides access to a shared informer and lister for
// ClusterPropagatedVersions.
type ClusterPropagatedVersionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterPropagatedVersionLister
}

type clusterPropagatedVersionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterPropagatedVersionInformer constructs a new informer for ClusterPropagatedVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterPropagatedVersionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterPropagatedVersionInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterPropagatedVersionInformer constructs a new informer for ClusterPropagatedVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterPropagatedVersionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().ClusterPropagatedVersions().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().ClusterPropagatedVersions().Watch(context.TODO(), options)
			},
		},
		&corev1alpha1.ClusterPropagatedVersion{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterPropagatedVersionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterPropagatedVersionInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterPropagatedVersionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corev1alpha1.ClusterPropagatedVersion{}, f.defaultInformer)
}

func (f *clusterPropagatedVersionInformer) Lister() v1alpha1.ClusterPropagatedVersionLister {
	return v1alpha1.NewClusterPropagatedVersionLister(f.Informer().GetIndexer())
}
