// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/kubewharf/kubeadmiral/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterOverridePolicies returns a ClusterOverridePolicyInformer.
	ClusterOverridePolicies() ClusterOverridePolicyInformer
	// ClusterPropagatedVersions returns a ClusterPropagatedVersionInformer.
	ClusterPropagatedVersions() ClusterPropagatedVersionInformer
	// ClusterPropagationPolicies returns a ClusterPropagationPolicyInformer.
	ClusterPropagationPolicies() ClusterPropagationPolicyInformer
	// FederatedClusters returns a FederatedClusterInformer.
	FederatedClusters() FederatedClusterInformer
	// FederatedTypeConfigs returns a FederatedTypeConfigInformer.
	FederatedTypeConfigs() FederatedTypeConfigInformer
	// OverridePolicies returns a OverridePolicyInformer.
	OverridePolicies() OverridePolicyInformer
	// PropagatedVersions returns a PropagatedVersionInformer.
	PropagatedVersions() PropagatedVersionInformer
	// PropagationPolicies returns a PropagationPolicyInformer.
	PropagationPolicies() PropagationPolicyInformer
	// SchedulerPluginWebhookConfigurations returns a SchedulerPluginWebhookConfigurationInformer.
	SchedulerPluginWebhookConfigurations() SchedulerPluginWebhookConfigurationInformer
	// SchedulingProfiles returns a SchedulingProfileInformer.
	SchedulingProfiles() SchedulingProfileInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClusterOverridePolicies returns a ClusterOverridePolicyInformer.
func (v *version) ClusterOverridePolicies() ClusterOverridePolicyInformer {
	return &clusterOverridePolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ClusterPropagatedVersions returns a ClusterPropagatedVersionInformer.
func (v *version) ClusterPropagatedVersions() ClusterPropagatedVersionInformer {
	return &clusterPropagatedVersionInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ClusterPropagationPolicies returns a ClusterPropagationPolicyInformer.
func (v *version) ClusterPropagationPolicies() ClusterPropagationPolicyInformer {
	return &clusterPropagationPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// FederatedClusters returns a FederatedClusterInformer.
func (v *version) FederatedClusters() FederatedClusterInformer {
	return &federatedClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// FederatedTypeConfigs returns a FederatedTypeConfigInformer.
func (v *version) FederatedTypeConfigs() FederatedTypeConfigInformer {
	return &federatedTypeConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// OverridePolicies returns a OverridePolicyInformer.
func (v *version) OverridePolicies() OverridePolicyInformer {
	return &overridePolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PropagatedVersions returns a PropagatedVersionInformer.
func (v *version) PropagatedVersions() PropagatedVersionInformer {
	return &propagatedVersionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PropagationPolicies returns a PropagationPolicyInformer.
func (v *version) PropagationPolicies() PropagationPolicyInformer {
	return &propagationPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SchedulerPluginWebhookConfigurations returns a SchedulerPluginWebhookConfigurationInformer.
func (v *version) SchedulerPluginWebhookConfigurations() SchedulerPluginWebhookConfigurationInformer {
	return &schedulerPluginWebhookConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// SchedulingProfiles returns a SchedulingProfileInformer.
func (v *version) SchedulingProfiles() SchedulingProfileInformer {
	return &schedulingProfileInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
