// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	corev1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	versioned "github.com/kubewharf/kubeadmiral/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubewharf/kubeadmiral/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/client/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SchedulingProfileInformer provides access to a shared informer and lister for
// SchedulingProfiles.
type SchedulingProfileInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SchedulingProfileLister
}

type schedulingProfileInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSchedulingProfileInformer constructs a new informer for SchedulingProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSchedulingProfileInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSchedulingProfileInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredSchedulingProfileInformer constructs a new informer for SchedulingProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSchedulingProfileInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().SchedulingProfiles().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().SchedulingProfiles().Watch(context.TODO(), options)
			},
		},
		&corev1alpha1.SchedulingProfile{},
		resyncPeriod,
		indexers,
	)
}

func (f *schedulingProfileInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSchedulingProfileInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *schedulingProfileInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corev1alpha1.SchedulingProfile{}, f.defaultInformer)
}

func (f *schedulingProfileInformer) Lister() v1alpha1.SchedulingProfileLister {
	return v1alpha1.NewSchedulingProfileLister(f.Informer().GetIndexer())
}
