// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterCollectedStatusLister helps list ClusterCollectedStatuses.
// All objects returned here must be treated as read-only.
type ClusterCollectedStatusLister interface {
	// List lists all ClusterCollectedStatuses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterCollectedStatus, err error)
	// Get retrieves the ClusterCollectedStatus from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ClusterCollectedStatus, error)
	ClusterCollectedStatusListerExpansion
}

// clusterCollectedStatusLister implements the ClusterCollectedStatusLister interface.
type clusterCollectedStatusLister struct {
	indexer cache.Indexer
}

// NewClusterCollectedStatusLister returns a new ClusterCollectedStatusLister.
func NewClusterCollectedStatusLister(indexer cache.Indexer) ClusterCollectedStatusLister {
	return &clusterCollectedStatusLister{indexer: indexer}
}

// List lists all ClusterCollectedStatuses in the indexer.
func (s *clusterCollectedStatusLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterCollectedStatus, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterCollectedStatus))
	})
	return ret, err
}

// Get retrieves the ClusterCollectedStatus from the index for a given name.
func (s *clusterCollectedStatusLister) Get(name string) (*v1alpha1.ClusterCollectedStatus, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clustercollectedstatus"), name)
	}
	return obj.(*v1alpha1.ClusterCollectedStatus), nil
}
