// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterPropagatedVersionLister helps list ClusterPropagatedVersions.
// All objects returned here must be treated as read-only.
type ClusterPropagatedVersionLister interface {
	// List lists all ClusterPropagatedVersions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterPropagatedVersion, err error)
	// Get retrieves the ClusterPropagatedVersion from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ClusterPropagatedVersion, error)
	ClusterPropagatedVersionListerExpansion
}

// clusterPropagatedVersionLister implements the ClusterPropagatedVersionLister interface.
type clusterPropagatedVersionLister struct {
	indexer cache.Indexer
}

// NewClusterPropagatedVersionLister returns a new ClusterPropagatedVersionLister.
func NewClusterPropagatedVersionLister(indexer cache.Indexer) ClusterPropagatedVersionLister {
	return &clusterPropagatedVersionLister{indexer: indexer}
}

// List lists all ClusterPropagatedVersions in the indexer.
func (s *clusterPropagatedVersionLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterPropagatedVersion, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterPropagatedVersion))
	})
	return ret, err
}

// Get retrieves the ClusterPropagatedVersion from the index for a given name.
func (s *clusterPropagatedVersionLister) Get(name string) (*v1alpha1.ClusterPropagatedVersion, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clusterpropagatedversion"), name)
	}
	return obj.(*v1alpha1.ClusterPropagatedVersion), nil
}
