// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterOverridePolicyListerExpansion allows custom methods to be added to
// ClusterOverridePolicyLister.
type ClusterOverridePolicyListerExpansion interface{}

// ClusterPropagatedVersionListerExpansion allows custom methods to be added to
// ClusterPropagatedVersionLister.
type ClusterPropagatedVersionListerExpansion interface{}

// ClusterPropagationPolicyListerExpansion allows custom methods to be added to
// ClusterPropagationPolicyLister.
type ClusterPropagationPolicyListerExpansion interface{}

// FederatedClusterListerExpansion allows custom methods to be added to
// FederatedClusterLister.
type FederatedClusterListerExpansion interface{}

// FederatedTypeConfigListerExpansion allows custom methods to be added to
// FederatedTypeConfigLister.
type FederatedTypeConfigListerExpansion interface{}

// OverridePolicyListerExpansion allows custom methods to be added to
// OverridePolicyLister.
type OverridePolicyListerExpansion interface{}

// OverridePolicyNamespaceListerExpansion allows custom methods to be added to
// OverridePolicyNamespaceLister.
type OverridePolicyNamespaceListerExpansion interface{}

// PropagatedVersionListerExpansion allows custom methods to be added to
// PropagatedVersionLister.
type PropagatedVersionListerExpansion interface{}

// PropagatedVersionNamespaceListerExpansion allows custom methods to be added to
// PropagatedVersionNamespaceLister.
type PropagatedVersionNamespaceListerExpansion interface{}

// PropagationPolicyListerExpansion allows custom methods to be added to
// PropagationPolicyLister.
type PropagationPolicyListerExpansion interface{}

// PropagationPolicyNamespaceListerExpansion allows custom methods to be added to
// PropagationPolicyNamespaceLister.
type PropagationPolicyNamespaceListerExpansion interface{}

// SchedulerPluginWebhookConfigurationListerExpansion allows custom methods to be added to
// SchedulerPluginWebhookConfigurationLister.
type SchedulerPluginWebhookConfigurationListerExpansion interface{}

// SchedulingProfileListerExpansion allows custom methods to be added to
// SchedulingProfileLister.
type SchedulingProfileListerExpansion interface{}
