// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterCollectedStatusListerExpansion allows custom methods to be added to
// ClusterCollectedStatusLister.
type ClusterCollectedStatusListerExpansion interface{}

// ClusterFederatedObjectListerExpansion allows custom methods to be added to
// ClusterFederatedObjectLister.
type ClusterFederatedObjectListerExpansion interface{}

// ClusterOverridePolicyListerExpansion allows custom methods to be added to
// ClusterOverridePolicyLister.
type ClusterOverridePolicyListerExpansion interface{}

// ClusterPropagatedVersionListerExpansion allows custom methods to be added to
// ClusterPropagatedVersionLister.
type ClusterPropagatedVersionListerExpansion interface{}

// ClusterPropagationPolicyListerExpansion allows custom methods to be added to
// ClusterPropagationPolicyLister.
type ClusterPropagationPolicyListerExpansion interface{}

// CollectedStatusListerExpansion allows custom methods to be added to
// CollectedStatusLister.
type CollectedStatusListerExpansion interface{}

// CollectedStatusNamespaceListerExpansion allows custom methods to be added to
// CollectedStatusNamespaceLister.
type CollectedStatusNamespaceListerExpansion interface{}

// FederatedClusterListerExpansion allows custom methods to be added to
// FederatedClusterLister.
type FederatedClusterListerExpansion interface{}

// FederatedObjectListerExpansion allows custom methods to be added to
// FederatedObjectLister.
type FederatedObjectListerExpansion interface{}

// FederatedObjectNamespaceListerExpansion allows custom methods to be added to
// FederatedObjectNamespaceLister.
type FederatedObjectNamespaceListerExpansion interface{}

// FederatedTypeConfigListerExpansion allows custom methods to be added to
// FederatedTypeConfigLister.
type FederatedTypeConfigListerExpansion interface{}

// OverridePolicyListerExpansion allows custom methods to be added to
// OverridePolicyLister.
type OverridePolicyListerExpansion interface{}

// OverridePolicyNamespaceListerExpansion allows custom methods to be added to
// OverridePolicyNamespaceLister.
type OverridePolicyNamespaceListerExpansion interface{}

// PropagatedVersionListerExpansion allows custom methods to be added to
// PropagatedVersionLister.
type PropagatedVersionListerExpansion interface{}

// PropagatedVersionNamespaceListerExpansion allows custom methods to be added to
// PropagatedVersionNamespaceLister.
type PropagatedVersionNamespaceListerExpansion interface{}

// PropagationPolicyListerExpansion allows custom methods to be added to
// PropagationPolicyLister.
type PropagationPolicyListerExpansion interface{}

// PropagationPolicyNamespaceListerExpansion allows custom methods to be added to
// PropagationPolicyNamespaceLister.
type PropagationPolicyNamespaceListerExpansion interface{}

// SchedulerPluginWebhookConfigurationListerExpansion allows custom methods to be added to
// SchedulerPluginWebhookConfigurationLister.
type SchedulerPluginWebhookConfigurationListerExpansion interface{}

// SchedulingProfileListerExpansion allows custom methods to be added to
// SchedulingProfileLister.
type SchedulingProfileListerExpansion interface{}
