// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FederatedTypeConfigLister helps list FederatedTypeConfigs.
// All objects returned here must be treated as read-only.
type FederatedTypeConfigLister interface {
	// List lists all FederatedTypeConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FederatedTypeConfig, err error)
	// Get retrieves the FederatedTypeConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FederatedTypeConfig, error)
	FederatedTypeConfigListerExpansion
}

// federatedTypeConfigLister implements the FederatedTypeConfigLister interface.
type federatedTypeConfigLister struct {
	indexer cache.Indexer
}

// NewFederatedTypeConfigLister returns a new FederatedTypeConfigLister.
func NewFederatedTypeConfigLister(indexer cache.Indexer) FederatedTypeConfigLister {
	return &federatedTypeConfigLister{indexer: indexer}
}

// List lists all FederatedTypeConfigs in the indexer.
func (s *federatedTypeConfigLister) List(selector labels.Selector) (ret []*v1alpha1.FederatedTypeConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FederatedTypeConfig))
	})
	return ret, err
}

// Get retrieves the FederatedTypeConfig from the index for a given name.
func (s *federatedTypeConfigLister) Get(name string) (*v1alpha1.FederatedTypeConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("federatedtypeconfig"), name)
	}
	return obj.(*v1alpha1.FederatedTypeConfig), nil
}
