// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FederatedClusterLister helps list FederatedClusters.
// All objects returned here must be treated as read-only.
type FederatedClusterLister interface {
	// List lists all FederatedClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FederatedCluster, err error)
	// Get retrieves the FederatedCluster from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FederatedCluster, error)
	FederatedClusterListerExpansion
}

// federatedClusterLister implements the FederatedClusterLister interface.
type federatedClusterLister struct {
	indexer cache.Indexer
}

// NewFederatedClusterLister returns a new FederatedClusterLister.
func NewFederatedClusterLister(indexer cache.Indexer) FederatedClusterLister {
	return &federatedClusterLister{indexer: indexer}
}

// List lists all FederatedClusters in the indexer.
func (s *federatedClusterLister) List(selector labels.Selector) (ret []*v1alpha1.FederatedCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FederatedCluster))
	})
	return ret, err
}

// Get retrieves the FederatedCluster from the index for a given name.
func (s *federatedClusterLister) Get(name string) (*v1alpha1.FederatedCluster, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("federatedcluster"), name)
	}
	return obj.(*v1alpha1.FederatedCluster), nil
}
