// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SchedulerPluginWebhookConfigurationLister helps list SchedulerPluginWebhookConfigurations.
// All objects returned here must be treated as read-only.
type SchedulerPluginWebhookConfigurationLister interface {
	// List lists all SchedulerPluginWebhookConfigurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.SchedulerPluginWebhookConfiguration, err error)
	// Get retrieves the SchedulerPluginWebhookConfiguration from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.SchedulerPluginWebhookConfiguration, error)
	SchedulerPluginWebhookConfigurationListerExpansion
}

// schedulerPluginWebhookConfigurationLister implements the SchedulerPluginWebhookConfigurationLister interface.
type schedulerPluginWebhookConfigurationLister struct {
	indexer cache.Indexer
}

// NewSchedulerPluginWebhookConfigurationLister returns a new SchedulerPluginWebhookConfigurationLister.
func NewSchedulerPluginWebhookConfigurationLister(indexer cache.Indexer) SchedulerPluginWebhookConfigurationLister {
	return &schedulerPluginWebhookConfigurationLister{indexer: indexer}
}

// List lists all SchedulerPluginWebhookConfigurations in the indexer.
func (s *schedulerPluginWebhookConfigurationLister) List(selector labels.Selector) (ret []*v1alpha1.SchedulerPluginWebhookConfiguration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SchedulerPluginWebhookConfiguration))
	})
	return ret, err
}

// Get retrieves the SchedulerPluginWebhookConfiguration from the index for a given name.
func (s *schedulerPluginWebhookConfigurationLister) Get(name string) (*v1alpha1.SchedulerPluginWebhookConfiguration, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("schedulerpluginwebhookconfiguration"), name)
	}
	return obj.(*v1alpha1.SchedulerPluginWebhookConfiguration), nil
}
