// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SchedulingProfileLister helps list SchedulingProfiles.
// All objects returned here must be treated as read-only.
type SchedulingProfileLister interface {
	// List lists all SchedulingProfiles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.SchedulingProfile, err error)
	// Get retrieves the SchedulingProfile from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.SchedulingProfile, error)
	SchedulingProfileListerExpansion
}

// schedulingProfileLister implements the SchedulingProfileLister interface.
type schedulingProfileLister struct {
	indexer cache.Indexer
}

// NewSchedulingProfileLister returns a new SchedulingProfileLister.
func NewSchedulingProfileLister(indexer cache.Indexer) SchedulingProfileLister {
	return &schedulingProfileLister{indexer: indexer}
}

// List lists all SchedulingProfiles in the indexer.
func (s *schedulingProfileLister) List(selector labels.Selector) (ret []*v1alpha1.SchedulingProfile, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SchedulingProfile))
	})
	return ret, err
}

// Get retrieves the SchedulingProfile from the index for a given name.
func (s *schedulingProfileLister) Get(name string) (*v1alpha1.SchedulingProfile, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("schedulingprofile"), name)
	}
	return obj.(*v1alpha1.SchedulingProfile), nil
}
