apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeadmiral-kube-controller-manager
  namespace: kubeadmiral-system
  labels:
    app: kubeadmiral-kube-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeadmiral-kube-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubeadmiral-kube-controller-manager
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kubeadmiral-kube-controller-manager
              topologyKey: kubernetes.io/hostname
      containers:
        - command:
            - kube-controller-manager
            - --allocate-node-cidrs=true
            - --authentication-kubeconfig=/etc/kubeconfig
            - --authorization-kubeconfig=/etc/kubeconfig
            - --bind-address=0.0.0.0
            - --client-ca-file=/etc/kubeadmiral/pki/ca.crt
            - --cluster-cidr=10.244.0.0/16
            - --cluster-name=kubeadmiral
            - --cluster-signing-cert-file=/etc/kubeadmiral/pki/ca.crt
            - --cluster-signing-key-file=/etc/kubeadmiral/pki/ca.key
            - --controllers=namespace,garbagecollector
            - --kubeconfig=/etc/kubeconfig
            - --leader-elect=true
            - --node-cidr-mask-size=24
            - --root-ca-file=/etc/kubeadmiral/pki/ca.crt
            - --service-account-private-key-file=/etc/kubeadmiral/pki/kubeadmiral.key
            - --service-cluster-ip-range=10.96.0.0/12
            - --use-service-account-credentials=true
            - --v=4
          image: registry.k8s.io/kube-controller-manager:v1.26.10
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /healthz
              port: 10257
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          name: kubeadmiral-kube-controller-manager
          resources:
            requests:
              cpu: 200m
          volumeMounts:
            - mountPath: /etc/kubeadmiral/pki
              name: kubeadmiral-certs
              readOnly: true
            - mountPath: /etc/kubeconfig
              subPath: kubeconfig
              name: kubeconfig
      priorityClassName: system-node-critical
      volumes:
        - name: kubeadmiral-certs
          secret:
            secretName: kubeadmiral-cert-secret
        - name: kubeconfig
          secret:
            secretName: kubeconfig
