apiVersion: v1
stringData:
  kubeconfig: |-
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {{ca_crt}}
        server: https://kubeadmiral-apiserver.kubeadmiral-system.svc.cluster.local:5443
      name: kind-kubeadmiral
    contexts:
    - context:
        cluster: kind-kubeadmiral
        user: kind-kubeadmiral
      name: kubeadmiral
    current-context: kubeadmiral
    kind: Config
    preferences: {}
    users:
    - name: kind-kubeadmiral
      user:
        client-certificate-data: {{client_crt}}
        client-key-data: {{client_key}}
  hpa-kubeconfig: |-
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {{ca_crt}}
        server: https://kubeadmiral-apiserver.kubeadmiral-system.svc.cluster.local:5443/apis/hpaaggregator.kubeadmiral.io/v1alpha1/aggregations/hpa/proxy
      name: kind-kubeadmiral
    contexts:
    - context:
        cluster: kind-kubeadmiral
        user: kind-kubeadmiral
      name: kubeadmiral
    current-context: kubeadmiral
    kind: Config
    preferences: {}
    users:
    - name: kind-kubeadmiral
      user:
        client-certificate-data: {{client_crt}}
        client-key-data: {{client_key}}
kind: Secret
metadata:
  name: kubeconfig
  namespace: kubeadmiral-system
