apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeadmiral-apiserver
  namespace: kubeadmiral-system
  labels:
    app: kubeadmiral-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeadmiral-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubeadmiral-apiserver
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kubeadmiral-apiserver
              topologyKey: kubernetes.io/hostname
      containers:
        - command:
            - kube-apiserver
            - --allow-privileged=true
            - --authorization-mode=Node,RBAC
            - --client-ca-file=/etc/kubeadmiral/pki/ca.crt
            - --enable-admission-plugins=NodeRestriction
            - --enable-bootstrap-token-auth=true
            - --enable-aggregator-routing=false # make sure ExternalName svc can work for HPA aggregator
            - --etcd-cafile=/etc/kubeadmiral/pki/etcd-ca.crt
            - --etcd-certfile=/etc/kubeadmiral/pki/etcd-client.crt
            - --etcd-keyfile=/etc/kubeadmiral/pki/etcd-client.key
            - --etcd-servers=https://etcd-client.kubeadmiral-system.svc.cluster.local:2379
            - --bind-address=0.0.0.0
            - --kubelet-client-certificate=/etc/kubeadmiral/pki/kubeadmiral.crt
            - --kubelet-client-key=/etc/kubeadmiral/pki/kubeadmiral.key
            - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
            - --disable-admission-plugins=StorageObjectInUseProtection,ServiceAccount
            - --runtime-config=
            - --secure-port=5443
            - --service-account-issuer=https://kubernetes.default.svc.cluster.local
            - --service-account-key-file=/etc/kubeadmiral/pki/kubeadmiral.key
            - --service-account-signing-key-file=/etc/kubeadmiral/pki/kubeadmiral.key
            - --service-cluster-ip-range=10.96.0.0/12
            - --proxy-client-cert-file=/etc/kubeadmiral/pki/front-proxy-client.crt
            - --proxy-client-key-file=/etc/kubeadmiral/pki/front-proxy-client.key
            - --requestheader-allowed-names=front-proxy-client
            - --requestheader-client-ca-file=/etc/kubeadmiral/pki/front-proxy-ca.crt
            - --requestheader-extra-headers-prefix=X-Remote-Extra-
            - --requestheader-group-headers=X-Remote-Group
            - --requestheader-username-headers=X-Remote-User
            - --tls-cert-file=/etc/kubeadmiral/pki/apiserver.crt
            - --tls-private-key-file=/etc/kubeadmiral/pki/apiserver.key
          name: kubeadmiral-apiserver
          image: registry.k8s.io/kube-apiserver:v1.20.15
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /livez
              port: 5443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 5443
              scheme: HTTPS
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 15
          resources:
            requests:
              cpu: 250m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/kubeadmiral/pki
              name: kubeadmiral-certs
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      enableServiceLinks: true
      hostNetwork: true
      preemptionPolicy: PreemptLowerPriority
      priority: 2000001000
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          operator: Exists
      volumes:
        - name: kubeadmiral-certs
          secret:
            secretName: kubeadmiral-cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: kubeadmiral-apiserver
  namespace: kubeadmiral-system
  labels:
    app: kubeadmiral-apiserver
spec:
  ports:
    - name: kubeadmiral-apiserver-kubectl
      port: 5443
      protocol: TCP
      targetPort: 5443
  selector:
    app: kubeadmiral-apiserver
  type: ClusterIP
